# Site settings
description: "O conhecimento que você precisa, do jeito que você quer"
baseurl: ""
url: "https://codeshare.com.br"
icon: https://raw.githubusercontent.com/CodeShareEducation/CodeShareEducation.github.io/master/src/img/icons/favicon.ico

# User settings
username: CodeShare
user_description: O conhecimento que você precisa, do jeito que você quer!
user_title: O conhecimento que você precisa, do jeito que você quer!
user_gravatar: d36a082aacb53b6f76869748fb4b81d4
email: wendelladriel.ti@gmail.com
github_username:  CodeShareEducation
gplus_username: CodeshareBrEducation
twitter_username: codeshare_br
disqus_username: codeshareeducation

authors:
  wendell:
    name: Wendell Adriel
    gravatar: d36a082aacb53b6f76869748fb4b81d4
    email: wendelladriel.ti@gmail.com
    github: WendellAdriel
    linkedin: wendelladrielti/en
    twitter: wendell_adriel
    facebook: wendell.adriel.7
    site: https://wendelladriel.com
    bio: "Criador da CodeShare, Engenheiro de Software, Palestrante, Escritor, Amante de PHP/JavaScript/Go/Open Source, Dungeon Master e Gamer"

  mcqueide:
    name: John Mc.Queide
    gravatar: cdb899949441a43c0479035ab5e5d5d9
    email: mcqueide@gmail.com
    github: mcqueide
    linkedin: mcqueide/en
    twitter:
    facebook:
    site:
    bio: "Sou Desenvolvedor Java, graduado em Análise e Desenvolvimento de Sistemas, possuo as certificações Java
    Programmer e Java Web Component Developer. Tenho 2 anos de experiência com desenvolvimento de software voltados para web.
    Gosto muito de ler, e compartilhar conhecimento com os que estão a minha volta, e estou sempre a procura de um maior crescimento."

  edson:
    name: Edson Junior
    gravatar: 95eef2ad27ac806bf77e5b837ddc47ec
    email: junior.si16@gmail.com
    github: roinuj16
    linkedin: roinuj16
    twitter: juniorsi16
    facebook: Roinuj16
    site: https://roinuj16.github.io/
    bio: "Sou desenvolvedor PHP, graduado em Sistemas de Informação e apaixonado por tecnologia, trabalho há mais de três anos como
    desenvolvedor PHP, gosto de aprimorar e atualizar meus conhecimentos e também gosto de trocar experiência e conhecimento com
    outras pessoas. O sucesso e a diversão que tenho no meu trabalho é imenso e mantém essa paixão ardentemente viva."

  claudio:
    name: Claudio Ribeiro
    gravatar: bde4c63167ba18607df504d7feefe16a
    email: claudio.santos.ribeiro@gmail.com
    github: DailyMatters
    linkedin: cl%C3%A1udio-ribeiro-16523750/
    twitter: ClauASRibeiro
    Facebook: claudio.santos.ribeiro.6
    site:
    bio: "Software developer, escritor e viajante de Lisboa. Quando não estou a viajar ou a escrever alguma peça acerca de desenvolvimento
    web podem encontrar-me algures a tentar ser um agente de disrupção e inovação!"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
highlighter: none
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

files_to_cache:
  - '/assets/js/main.js'
  - '/assets/css/main.css'
  - '/assets/css/prism.css'
  - '/assets/img/blog-image.png'
  - '/assets/img/offline.jpg'

pages_to_cache:
  - '/autores/'
  - '/categorias/'
  - '/sobre/'
  - '/tags/'
  - '/offline/index.html'

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Autores
    url: /autores
  - title: Categorias
    url: /categorias
  - title: Tags
    url: /tags
  - title: Sobre
    url: /sobre


# exclude my node related stuff
exclude: [
  'package.json',
  'src',
  'node_modules',
  'vendor/bundle/ruby',
  'package-lock.json',
  'README.md',
  'gulpfile.js',
  'initpost.sh'
]

include: ['_redirects', '_headers']